### ISSUE TITLE
Better documentation layout/design

### ISSUE THREAD

**Issue by augustohp** [Respect/respect.github.com#6]
Would be great if we could still use the README.md and make it more useful.

**Comment by henriquemoody** [comment]
The entire layout has been updated.

Now it's taking information about the repositories from the GitHub API and sorting it according to the most recently updated repository (by _updated_ I mean pushes on the repository). Also, it's making cache of the request by web browser session storage in order to avoid too many requests to the GitHub API.

The translation schema has been updated to, now it loads information from a JSON schema instead of hiding and showing HTML elements, also it stores the last selected language by session storage in order to translate the page after refresh it.

I'm not sure this issue was closed to you guys, but due the time and the recent changes I will close it, any way, you all have the privilege to reopen it or create a new one.

Cheers!

**Comment by alganet** [comment]
:panda_face:
